#!/usr/bin/env sh

branch="$(git branch --show-current)"

if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
  echo "=================================================="
  echo "Error: Direct commits to '$branch' are not allowed."
  echo "Please create a new branch for your feature or fix."
  echo "=================================================="
  exit 1
fi
